### ISSUE TITLE
Timezone for conversion

### ISSUE THREAD

**Issue by anirudhsamudrala** [oanda/csharp-exchange-rates#2]
If I query the API to get the currency conversion done and the I pass in a date as parameter, what time zone does the API take into consideration while returning result?

**Comment by paul-vanhout** [comment]
From the OANDA Exchange Rate API documentation:
date – A specific quote date

format: (string) In the format YYYY-MM-DD
**Dates are interpreted in UTC time zone**
Date specified must be less than or equivalent to today’s date
default: The current day (UTC time zone)
NOTE: Omitting this paramter or specifying today’s date returns the latest quotes available. If today’s quotes exist, they are returned, otherwise the API returns the latest quotes available.
The date parameter is ignored if start and end are used to request a date range
example: request EUR/USD for January 1, 2014 curl -X GET "https://web-services.oanda.com/rates/api/v1/rates/EUR.json?quote=USD&date=2014-01-01"

**Comment by anirudhsamudrala** [comment]
Thanks @paul-vanhout
